name: Github Page

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Packages
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - name: Build
        working-directory: ./sb_article_categories
        env:
          BASE_PATH: /sb_article_categories
        run: |
          echo "" > .env.local
          echo BASE_PATH=$BASE_PATH >> .env.local
          pnpm run build
      - name: Create .nojekyll
        run: touch ./sb_article_categories/out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: sb_article_categories/out
